import { auth } from "../auth";
import Sidemenu from "../components/Sidemenu";
import "./globals.css";
import {
  Merriweather,
  Source_Sans_3,
} from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "./ThemeProvider";
import { DataProvider } from "./DataProvider";

const crimson_test = Merriweather({
  weight: ["300", "700", "900"],
  subsets: ["latin"],
});

const open_sans_font = Source_Sans_3({
  weight: ["200", "300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Sain Packaging",
  description: "Generated by the Great",
  keywords: ["Sain Packaging", "Dashboard", "Job Dashboard"],
};

const scriptURL = "https://script.google.com/macros/s/AKfycbwyQEojQ3oPDKFgw9hDXz_8BDgtEw1WbM9diSOR1u6nhktzw9ZFqINgUT9vGWdJj8E7/exec";

// This runs on the server!
async function getSettingsFromAPI() {
  const res = await fetch(scriptURL, {
    // next: { revalidate: 300 }, // revalidate every 5 minutes
  });
  const data = await res.json();
  return data;
}

export default async function RootLayout({ children }) {
  const session = await auth();
  const data = await getSettingsFromAPI();
  // console.log("Settings data:", data);

  // console.log("IM running on the server");

  return (
    <html lang="en">
      <SessionProvider session={children.session}>
        <body className={open_sans_font.className}>
          <ThemeProvider>
            <DataProvider data={data}>
              <>
                <div style={{ display: "flex" }}>
                  <Sidemenu />
                  <div className="layoutRightDiv">
                    {children}
                  </div>
                </div>
              </>
            </DataProvider>
          </ThemeProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
