// app/layout.jsx or layout.tsx
import { auth } from "../auth";
import Sidemenu from "../components/Sidemenu";
import "./globals.css";
import { Merriweather, Source_Sans_3 } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "./ThemeProvider";
import { DataProvider } from "./DataProvider";

// Fonts
const merriweather = Merriweather({
  weight: ["300", "700", "900"],
  subsets: ["latin"],
});

const sourceSans = Source_Sans_3({
  weight: ["200", "300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Sain Packaging",
  description: "Generated by the Great",
  keywords: ["Sain Packaging", "Dashboard", "Job Dashboard"],
};

const scriptURL = "https://script.google.com/macros/s/AKfycbwyQEojQ3oPDKFgw9hDXz_8BDgtEw1WbM9diSOR1u6nhktzw9ZFqINgUT9vGWdJj8E7/exec";

async function getSettingsFromAPI() {
  const res = await fetch(scriptURL);
  const data = await res.json();
  return data;
}

export default async function RootLayout({ children }) {
  const session = await auth();
  const settings = await getSettingsFromAPI();

  return (
    <html lang="en" className={sourceSans.className}>
      <SessionProvider session={session}>
        <body>
          <ThemeProvider>
            <DataProvider data={settings}>
              <div className="layoutWrapper">
                <Sidemenu />
                <div className="layoutRightDiv">{children}</div>
              </div>
            </DataProvider>
          </ThemeProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
