
import Sidemenu from "../components/Sidemenu";
// import "";
import {
    Merriweather,
    Source_Sans_3,
    Open_Sans,
    Noto_Sans,
    Noto_Sans_Tamil_Supplement,
} from "next/font/google";
import { SessionProvider } from "next-auth/react";
import ThemeProvider from "./ThemeProvider";
import Head from "next/head";

const crimson_test = Merriweather({
    weight: ["300", "700", "900"],
    subsets: ["latin"],
});

const open_sans_font = Source_Sans_3({
    weight: ["200", "300", "400", "500", "600"],
    subsets: ["latin"],
});

export const metadata = {
    title: "Sain Packaging",
    description: "Generated by the Great",
    keywords: ["Sain Packaging", "Dashboard", "Job Dashboard"],
};

export default async function RootLayout({ children }) {

    return (
        <>
            <div style={{ display: "flex" }}>
                <Sidemenu />
                <div className="layoutRightDiv">
                    {children}
                </div>
            </div>
        </>
    );

}
